# Generated by Django 4.0.3 on 2022-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('RegdNo',models.CharField(max_length=200,blank=True,null=True)),
                ('YearOfAdmission',models.IntegerField(unique=True,blank=True,null=True)),
                ('medicalCouncil',models.CharField(max_length=200,blank=True,null=True)),
                ('photo',models.ImageField(blank=True,null=True)),
                ('signature',models.ImageField(blank=True,null=True)),
                ('regdCertificate',models.ImageField(blank=True,null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tc',models.BooleanField())
            ],
            options={
                'abstract': False,
            },
        ),
    ]
