# Generated by Django 4.0.3 on 2022-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
