# Generated by Django 4.0.3 on 2022-06-13 13:57

from django.db import migrations,models



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='RegdNo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='YearOfAdmission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medicalCouncil',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='regdCertificate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signature',
        ),
    ]
