# Generated by Django 4.0.3 on 2022-06-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_yearofadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='YearOfAdmission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
