# Generated by Django 4.0.3 on 2022-06-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_prescription', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='write_prescription_model',
        ),
    ]
