# Generated by Django 4.0.3 on 2022-06-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_prescription', '0002_rename_model_write_prescription_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='write_prescription_model',
            new_name='Prescription',
        ),
    ]
