# Generated by Django 4.0.3 on 2022-06-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_prescription', '0003_rename_write_prescription_model_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='timing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='when_to_eat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
