# Generated by Django 4.0.3 on 2022-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_prescription', '0004_prescription_doses_prescription_medicines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dignosed_with',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
