# Generated by Django 4.0.3 on 2022-06-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_prescription', '0005_medicine_remove_prescription_medicines_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicine',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
